#!/usr/bin/perl
use strict;
use warnings;

use FindBin qw($Bin);
use File::Find ();
use Test::More;

# ---------------------------------------------------------------------------
# Documentation hygiene guard
#
# Tracked files must not carry internal issue-tracker IDs or working dates:
# the public GitHub tree is a byte-for-byte copy of the internal one, so
# anything committed here ships to customers. Describe the behavior and the
# release version instead ("fixed in 0.2.1").
#
# Dates are allowed in debian/changelog, where each entry legitimately
# carries its release timestamp.
# ---------------------------------------------------------------------------

my $repo = "$Bin/..";

# Assembled at runtime so this file does not match its own pattern.
my $ticket_tag  = 'QS' . 'TOR';
my $ticket_re   = qr/\b\Q$ticket_tag\E-\d+/;
my $date_re     = qr/\b20\d\d-\d\d-\d\d\b/;

my @scan = qw(src t www debian README.md build-deb.sh .gitignore);

# Generated by dpkg-buildpackage / dh — copies of tracked files, not sources.
my $skip_re = qr{(?:^|/)(?:\.git|pve-storage-quantastor|\.debhelper)(?:/|$)};

sub scan_files {
    my @files;
    for my $entry (@scan) {
        my $path = "$repo/$entry";
        next unless -e $path;
        if (-f $path) {
            push @files, $entry;
            next;
        }
        File::Find::find({
            no_chdir => 1,
            wanted   => sub {
                my $abs = $File::Find::name;
                (my $rel = $abs) =~ s{^\Q$repo\E/}{};
                return if $rel =~ $skip_re;
                return unless -f $abs;
                return if -B $abs;    # skip binaries
                push @files, $rel;
            },
        }, $path);
    }
    return sort @files;
}

my @files = scan_files();
ok(scalar @files, 'found tracked files to scan') or done_testing(), exit;

my (@ticket_hits, @date_hits);

for my $rel (@files) {
    open my $fh, '<', "$repo/$rel" or die "open $rel: $!";
    while (my $line = <$fh>) {
        push @ticket_hits, "$rel:$.: $line" if $line =~ $ticket_re;
        next if $rel eq 'debian/changelog';
        push @date_hits, "$rel:$.: $line" if $line =~ $date_re;
    }
    close $fh;
}

is_deeply(\@ticket_hits, [],
    "no issue-tracker IDs in tracked files (@{[ scalar @files ]} scanned)")
    or diag("Offending lines:\n@ticket_hits");

is_deeply(\@date_hits, [],
    'no working dates in tracked files (debian/changelog exempt)')
    or diag("Offending lines:\n@date_hits");

done_testing();
